### ISSUE TITLE
프로젝트 기본 설계 문서 관리

### ISSUE THREAD

**Issue by mysend12** [java-book-study/java-tdd-web-app#1]
지금 생각나는 선택지는 일단 3가지.
1. documents 브랜치 생성해서 깃에서 관리
2. 구글 드라이브를 이용하여 관리
3. 둘 다 이용 ( 구글 드라이브에서 수정하고 깃에 올리기 )

1번은 이력관리가 쉽다는 장점이 있는 반면 수정이 어렵고,
2번은 수정이 쉬운 반면 이력 관리가 애매하다.
3번은.......

좋은 의견 부탁드립니다.

**Comment by ahnzhx** [comment]
1번이 좋은 것 같습니다!
